version: '3.9'

services:
  user_service:
    build: ./backend/user_service
    container_name: user_service
    ports:
      - "8000:8000"
    env_file:
      - ./backend/user_service/.env
    depends_on:
      - mysql

  manga_service:
    build: ./backend/manga_service
    container_name: manga_service
    ports:
      - "8001:8000"
    env_file:
      - ./backend/manga_service/.env
    depends_on:
      - mysql

  rating_service:
    build: ./backend/rating_service
    container_name: rating_service
    ports:
      - "8002:8000"
    env_file:
      - ./backend/rating_service/.env
    depends_on:
      - mysql

  recom_service:
    build: ./backend/recom_service
    container_name: recom_service
    ports:
      - "8003:8000"
    env_file:
      - ./backend/recom_service/.env

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8000"
    env_file:
      - ./gateway/.env
    depends_on:
      - user_service
      - manga_service
      - rating_service
      - recom_service

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagepuff
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
