services:
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"
    env_file:
      - ./user_service/.env
    depends_on:
      - mysql
      - init_db
    volumes:
      - ./user_service:/app
    command: uvicorn app.main:pagepuff --host 0.0.0.0 --port 8000 --reload

  manga_service:
    build: ./manga_service
    container_name: manga_service
    ports:
      - "8001:8000"
    env_file:
      - ./manga_service/.env
    depends_on:
      - mysql
      - init_db
    volumes:
      - ./manga_service:/app

  recom_service:
    build: ./recom_service
    container_name: recom_service
    ports:
      - "8003:8000"
    env_file:
      - ./recom_service/.env
    depends_on:
      - mysql
      - init_db
    volumes:
      - ./recom_service:/app

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8081:8000"
    env_file:
      - ./gateway/.env
    depends_on:
      - user_service
      - manga_service
      - recom_service
    volumes:
      - ./gateway:/app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagepuff
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init_all_tables.sql:/docker-entrypoint-initdb.d/00-init-all-tables.sql
      - ./manga_service/sql/MANGAPOPULATE.sql:/docker-entrypoint-initdb.d/01-populate-mangas.sql

  init_db:
    build: ./init_db_service
    container_name: init_db
    depends_on:
      - mysql
    volumes:
      - ./sql/init_all_tables.sql:/init-scripts/init_all_tables.sql
      - ./manga_service/sql/MANGAPOPULATE.sql:/init-scripts/MANGAPOPULATE.sql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=pagepuff
    restart: "no"

volumes:
  mysql_data:
