version: "3.8"

services:
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"
    env_file:
      - ./user_service/.env
    depends_on:
      - mysql
    volumes:
      - ./user_service:/app

  manga_service:
    build: ./manga_service
    container_name: manga_service
    ports:
      - "8001:8000"
    env_file:
      - ./manga_service/.env
    depends_on:
      - mysql
    volumes:
      - ./manga_service:/app

  rating_service:
    build: ./rating_service
    container_name: rating_service
    ports:
      - "8002:8000"
    env_file:
      - ./rating_service/.env
    depends_on:
      - mysql
    volumes:
      - ./rating_service:/app

  recom_service:
    build: ./recom_service
    container_name: recom_service
    ports:
      - "8003:8000"
    env_file:
      - ./recom_service/.env
    volumes:
      - ./recom_service:/app

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8000"
    env_file:
      - ./gateway/.env
    depends_on:
      - user_service
      - manga_service
      - rating_service
      - recom_service
    volumes:
      - ./gateway:/app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagepuff
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # 🔽 Todos os scripts .sql colocados aqui serão executados AUTOMATICAMENTE
      - ./user_service/sql:/docker-entrypoint-initdb.d/user
      - ./manga_service/sql:/docker-entrypoint-initdb.d/manga
      - ./rating_service/sql:/docker-entrypoint-initdb.d/rating

volumes:
  mysql_data:
